### ISSUE TITLE
Cyrillic letter Ъ transliterate it to #.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/cyrillic-transliteration#14]
This was raised in #12 by @097115. To reproduce this issue:
```bash
python cyrtranslit.py -l RU -i tests/ru.txt
```

**Comment by Syndamia** [comment]
If anyone wants to fix this issue, the fix is simple, you just need to change the appropriate character in the dictionaries:
https://github.com/opendatakosovo/cyrillic-transliteration/blob/7161458a261a99ada0b838aa0aa79a3bbc42886e/cyrtranslit/mapping.py#L116
https://github.com/opendatakosovo/cyrillic-transliteration/blob/7161458a261a99ada0b838aa0aa79a3bbc42886e/cyrtranslit/mapping.py#L130

and update the test:
https://github.com/opendatakosovo/cyrillic-transliteration/blob/7161458a261a99ada0b838aa0aa79a3bbc42886e/tests.py#L16

**But** there is a caveat, looking at the [Wikipedia page for Russian romanization](https://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table) there seem to be a couple of standards and the main ways to show `ъ` is with `ie`, `-` and `"`. I'm not Russian, not do I know the language, so someone more knowledgeable should decide which one of these is most appropriate.

**Important:** if you're gonna use the `ie`, don't forget to add the following line

```python
(c in u'Ii' and c_plus_1 in u'Ee')   or  # IE, ie 
```

in the `to_cyrillic function in __init__.py`:

https://github.com/opendatakosovo/cyrillic-transliteration/blob/7161458a261a99ada0b838aa0aa79a3bbc42886e/cyrtranslit/__init__.py#L106-L115

**Comment by georgeslabreche** [comment]
Thank you for your insights! Feel free to make an assumption to the best of your knowledge and create a pull request!
